name: goreleaser

on:
  push:
    tags:
      - '*'


permissions:
  contents: write
  # packages: write
  # issues: write

env:
  TAG_NAME: ${{ github.ref_name }}
  FURY_ACCOUNT: "huyongqii"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: create and publish release
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: |
          git fetch --force --tags
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libbtrfs-dev \
            libdevmapper-dev

      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --config ${{ github.workspace }}/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}


      - name: publish .exe assets
        uses: actions/upload-artifact@v3
        with:
          name: kbcli
          path: |
            ${{ github.workspace }}/dist/kbcli_windows_amd64_v1/*
            ${{ github.workspace }}/dist/kbcli_windows_arm64/*
